[workspace]
authors = ["Mikkel Roald-Arb√∏l <github.ggb9a@simplelogin.co>"]
channels = ["conda-forge"]
name = "animaltracking-forge"
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]
version = "0.1.0"

[dependencies]
rattler-build = "*"
